apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tristian-id.fullname" . }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "tristian-id.labels" . | nindent 6 }}